server:
  port: ${PORT:5000}

base-url: /api

spring:
  application:
    name: hexletBlog

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  jpa:
    hibernate:
      ddl-auto: create-drop