server:
  error:
    include-message: always
    include-exception: true
    include-stacktrace: never

spring:
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false

  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/tmdb
#    username: masha
#    password: good
#    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    ROOT: INFO
